FROM mcr.microsoft.com/dotnet/sdk:10.0-azurelinux3.0-amd64 AS build
WORKDIR /App
# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:10.0-azurelinux3.0-amd64
WORKDIR /App
EXPOSE 80
COPY --from=build /App/out .
ENTRYPOINT ["dotnet", "IngressoJa.dll"]
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=development

#docker build -t backend-ingressoja .