# Estágio de Build
FROM mcr.microsoft.com/dotnet/sdk:10.0-azurelinux3.0-amd64 AS build
WORKDIR /App

# 1. Copia APENAS o arquivo de projeto primeiro (O Segredo do Cache!)
COPY *.csproj ./
RUN dotnet restore

# 2. Agora copia o resto do código da aplicação
COPY . ./

# 3. Compila e publica
RUN dotnet publish -c Release -o out

# Estágio de Runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0-azurelinux3.0-amd64
WORKDIR /App
EXPOSE 80

# Copia os arquivos compilados do estágio anterior
COPY --from=build /App/out .

# Define apenas as portas. Deixe o Environment ser injetado pelo docker-compose!
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "IngressoJa.dll"]


